# Generated by Django 5.2.13 on 2026-04-29 00:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casefile', '0002_anesthesiacase_decision_and_more'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(blank=True, help_text='A+, B-, etc.', max_length=10, null=True)),
                ('weight', models.FloatField(blank=True, help_text='kg', null=True)),
                ('height', models.FloatField(blank=True, help_text='cm', null=True)),
                ('bmi', models.FloatField(blank=True, help_text='Calculated', null=True)),
                ('notes', models.TextField(blank=True, help_text='Résumé clinique important')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Medical Record',
                'db_table': 'medical_records',
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CARDIAC', 'Cardiaque'), ('PULMONARY', 'Pulmonaire'), ('METABOLIC', 'Métabolique'), ('NEUROLOGIC', 'Neurologique'), ('SURGICAL', 'Chirurgical'), ('MEDICATION', 'Médicamenteux'), ('ALLERGY', 'Allergie'), ('OTHER', 'Autre')], max_length=20)),
                ('description', models.TextField(help_text="Description de l'antécédent")),
                ('date_occurrence', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Toujours pertinent ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_items', to='dme.medicalrecord')),
            ],
            options={
                'db_table': 'medical_history',
                'ordering': ['-date_occurrence'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icd10_code', models.CharField(help_text='ICD-10 code', max_length=10)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critique'), ('HIGH', 'Élevée'), ('MODERATE', 'Modérée'), ('LOW', 'Faible')], default='MODERATE', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('confirmed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anesthesia_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to='casefile.anesthesiacase')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='dme.medicalrecord')),
            ],
            options={
                'db_table': 'diagnoses',
                'ordering': ['-severity', '-confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergen', models.CharField(help_text='e.g., Penicillin, Peanuts', max_length=255)),
                ('reaction', models.TextField(help_text='Description de la réaction')),
                ('severity', models.CharField(choices=[('MILD', 'Légère'), ('MODERATE', 'Modérée'), ('SEVERE', 'Grave'), ('LIFE_THREATENING', 'Menaçante pour la vie')], max_length=20)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='dme.medicalrecord')),
            ],
            options={
                'db_table': 'allergies',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(help_text='e.g., 500mg', max_length=100)),
                ('route', models.CharField(choices=[('IV', 'Intraveineuse'), ('PO', 'Per os'), ('IM', 'Intramusculaire'), ('SC', 'Sous-cutanée'), ('INHAL', 'Inhalation'), ('TOPICAL', 'Topique')], max_length=20)),
                ('frequency', models.CharField(help_text='e.g., 3x daily', max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('COMPLETED', 'Complété'), ('DISCONTINUED', 'Arrêté'), ('SUSPENDED', 'Suspendu')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Contra-indications, interactions, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anesthesia_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='casefile.anesthesiacase')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='dme.medicalrecord')),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('REPORT', 'Rapport médical'), ('LAB_RESULT', 'Résultat de labo'), ('IMAGING', 'Image médicale'), ('ECG', 'ECG'), ('CHART', 'Feuille de soins'), ('NOTE', 'Note clinique'), ('PRESCRIPTION', 'Ordonnance'), ('CONSENT', 'Consentement'), ('OTHER', 'Autre')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/')),
                ('file_url', models.URLField(blank=True, help_text='External URL if not stored locally')),
                ('document_date', models.DateField()),
                ('created_by', models.CharField(blank=True, help_text='Provider name', max_length=255)),
                ('is_confidential', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anesthesia_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_documents', to='casefile.anesthesiacase')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dme.medicalrecord')),
            ],
            options={
                'db_table': 'clinical_documents',
                'ordering': ['-document_date'],
                'indexes': [models.Index(fields=['medical_record', '-document_date'], name='clinical_do_medical_3971d2_idx'), models.Index(fields=['document_type', 'document_date'], name='clinical_do_documen_9ef537_idx')],
            },
        ),
    ]
