# Generated by Django 5.2.13 on 2026-04-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, help_text='Adresse complète', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, help_text='A+, A-, B+, B-, AB+, AB-, O+, O-', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text="Nom du contact en cas d'urgence", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text="Téléphone du contact d'urgence", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, help_text='Relation (ex: conjoint, parent)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_card_number',
            field=models.CharField(blank=True, help_text="Numéro de carte d'identité nationale", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_alcohol_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_smoker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='nationality',
            field=models.CharField(blank=True, default='Algérienne', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Le patient a complété son profil initial'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone principal', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='physical_activity',
            field=models.CharField(blank=True, choices=[('NONE', 'Sédentaire'), ('LIGHT', 'Légère'), ('MODERATE', 'Modérée'), ('INTENSE', 'Intense')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('OTHER', 'Autre')], default='M', max_length=20),
        ),
    ]
