# Generated by Django 5.2.13 on 2026-04-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_add_patient_id_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, help_text='Department/Unit', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'Médecin'), ('IADE', 'IADE (Infirmier Anesthésiste)'), ('SSPI', 'Équipe SSPI (Salle Surveillance Post-Intervention)'), ('ADMIN', 'Administrateur'), ('PATIENT', 'Patient')], default='PATIENT', max_length=10),
        ),
    ]
